### ISSUE TITLE
Twitter embedding sometimes crashes the bot

### ISSUE THREAD

**Issue by sweetsbeats** [Soreil/yuudachi#13]
Attempting to embed this tweet: https://twitter.com/nineetales/status/1128298108192993281
Will give back this error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6a81b9]

goroutine 60 [running]:
main.embedImages(0xc042088ea0, 0xc042142058, 0xc0420181e9, 0x39)
        C:/path/to/yuudachi/twitter.go:68 +0x289
main.command(0xc042088ea0, 0xc042142058)
        C:/path/to/yuudachi/discord.go:38 +0x1830
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x789c88, 0xc042088ea0, 0x703b20, 0xc042142058)
        C:/path/to/Go/src/github.com/bwmarrin/discordgo/eventhandlers.go:497 +0x5e
created by github.com/bwmarrin/discordgo.(*Session).handle
        C:/path/to/Go/src/github.com/bwmarrin/discordgo/event.go:171 +0x118

I've had this happen with a few other tweets, but most of them work otherwise. Nothing at the front end seems to be amiss, which is concerning.

**Comment by sweetsbeats** [comment]
I've come to find that (for this tweet at least) the tweet.ExtendedEntities.Media is nil, and is being accessed at runtime causing the error. I'm still digging into __why__ it's nil, which is proving to be a pain.
